/*
 Nama:Alya Septriasa
 kelas: tekom1B
 */
package Praktikum18062026;

import javax.swing.JOptionPane;

/**
 *
 * @author alyas
 */
public class FromNilai extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FromNilai.class.getName());

    /**
     * Creates new form FromNilai
     */
    public FromNilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        lblMatkul = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtMatkul = new javax.swing.JTextField();
        lblNilaiQuis = new javax.swing.JLabel();
        lblNilaiTugas = new javax.swing.JLabel();
        lblNilaiUts = new javax.swing.JLabel();
        lblNilaiUas = new javax.swing.JLabel();
        txtNilaiQuiz = new javax.swing.JTextField();
        txtNilaiTugas = new javax.swing.JTextField();
        txtNilaiUts = new javax.swing.JTextField();
        txtNilaiUas = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        lblNilaiAkhir = new javax.swing.JLabel();
        lblKonversi = new javax.swing.JLabel();
        txtNilaiAkhir = new javax.swing.JTextField();
        txtKonversi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJudul.setText("FORM PENILAIAN SISWA");

        lblNama.setText("Nama Mahasiswa");

        lblKelas.setText("Kelas");

        lblMatkul.setText("Mata Kuliah");

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtNama.addActionListener(this::txtNamaActionPerformed);

        txtKelas.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtKelas.addActionListener(this::txtKelasActionPerformed);

        txtMatkul.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        lblNilaiQuis.setText("Nilai Quiz");

        lblNilaiTugas.setText("Nilai Tugas");

        lblNilaiUts.setText("Nilai Uts");

        lblNilaiUas.setText("Nilai Uas");

        txtNilaiTugas.addActionListener(this::txtNilaiTugasActionPerformed);

        txtNilaiUas.addActionListener(this::txtNilaiUasActionPerformed);

        btnProses.setText("Proses");
        btnProses.addActionListener(this::btnProsesActionPerformed);

        lblNilaiAkhir.setText("Nilai Akhir");

        lblKonversi.setText("Konversi");

        txtNilaiAkhir.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        txtKonversi.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNama)
                            .addComponent(lblKelas)
                            .addComponent(lblMatkul)
                            .addComponent(lblNilaiQuis)
                            .addComponent(lblNilaiTugas)
                            .addComponent(lblNilaiUts)
                            .addComponent(lblNilaiUas))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNilaiUas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtKelas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMatkul))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNilaiQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNilaiUts, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(202, 202, 202)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNilaiAkhir)
                                            .addComponent(lblKonversi))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(btnProses))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(lblJudul)))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelas)
                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatkul)
                    .addComponent(txtMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNilaiQuis)
                            .addComponent(txtNilaiQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNilaiTugas)
                            .addComponent(txtNilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNilaiAkhir)
                            .addComponent(txtNilaiAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNilaiUts)
                            .addComponent(txtNilaiUts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKonversi)
                            .addComponent(txtKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNilaiUas)
                            .addComponent(txtNilaiUas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnProses)))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKelasActionPerformed

    private void txtNilaiTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNilaiTugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNilaiTugasActionPerformed

    private void txtNilaiUasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNilaiUasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNilaiUasActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText();
        String kelas = txtKelas.getText();
        String matkul = txtMatkul.getText();
        
        if(nama.isEmpty()||kelas.isEmpty()||matkul.isEmpty()){
            JOptionPane.showMessageDialog(this,"Data nama tidak boleh kosong");
            txtNama.requestFocus();
        }
        
        if (txtNilaiQuiz.getText().isEmpty()||txtNilaiTugas.getText().isEmpty()||txtNilaiUts.getText().isEmpty()||txtNilaiUas.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Nilai harus diisikan!!");
        }
        
        try{
            
        
        double quiz = validasiNilai(txtNilaiQuiz.getText(),"Quiz");
        double tugas = validasiNilai(txtNilaiTugas.getText(),"Tugas");
        double uts = validasiNilai(txtNilaiUts.getText(),"Uts");
        double uas = validasiNilai(txtNilaiUas.getText(),"Uas");
        
        double na = 0.15*quiz+0.2*tugas+0.3*uts+0.35*uas;
        
        txtNilaiAkhir.setText(Double.toString(na));
        txtKonversi.setText(KonversiNilai(na));
        
        JOptionPane.showMessageDialog(this,
                "\nnama"+nama+
                "\nkelas"+kelas+
                "\nmendapat nilai"+na+
                "atau setara dengan"+KonversiNilai(na)+
                "\nuntuk mata kuliah"+matkul,
                 "Hasil Penilaian",JOptionPane.INFORMATION_MESSAGE );
        
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Nilai harus berupa angka","peringatan",JOptionPane.ERROR_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage(),"Pengecekan Nilai",JOptionPane.WARNING_MESSAGE);
        }finally{
            JOptionPane.showMessageDialog(this,"pengecekan selesai");
        }      
    }//GEN-LAST:event_btnProsesActionPerformed
     
    private double validasiNilai(String input,String jenisNilai) throws Exception {
        double nilai = Double.parseDouble(input);
        if (nilai<0 || nilai >100)
            throw new Exception (jenisNilai+"harus antara 0-100");
        return nilai;
    }
    
    
    
    
    
    
    
    
    
    
    
    private String KonversiNilai(double nilai){
        if (nilai>=80)
            return "A";
        else if (nilai>=65)
            return "B";
        else if (nilai>=55)
            return "C";
        else if (nilai>=40)
            return "D";
        else 
            return "E";
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FromNilai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblKonversi;
    private javax.swing.JLabel lblMatkul;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNilaiAkhir;
    private javax.swing.JLabel lblNilaiQuis;
    private javax.swing.JLabel lblNilaiTugas;
    private javax.swing.JLabel lblNilaiUas;
    private javax.swing.JLabel lblNilaiUts;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtKonversi;
    private javax.swing.JTextField txtMatkul;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNilaiAkhir;
    private javax.swing.JTextField txtNilaiQuiz;
    private javax.swing.JTextField txtNilaiTugas;
    private javax.swing.JTextField txtNilaiUas;
    private javax.swing.JTextField txtNilaiUts;
    // End of variables declaration//GEN-END:variables
}
