/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Praktikum25062026;

import javax.swing.JOptionPane;

/**
 *
 * @author alyas
 */
public class FromKaryawan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FromKaryawan.class.getName());

    /**
     * Creates new form FromKaryawan
     */
    public FromKaryawan() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(240, 248, 255));
         btnHitung.setBackground(new java.awt.Color(76, 175, 80));
         btnHitung.setForeground(java.awt.Color.WHITE);
         btnReset.setBackground(new java.awt.Color(255,193,7));
         btnReset.setForeground(java.awt.Color.BLACK);
         btnKeluar.setBackground(new java.awt.Color(255,193,7));
         btnKeluar.setForeground(java.awt.Color.BLACK);
         cbGol.setBackground(new java.awt.Color(76, 175, 80));
         cbGol.setForeground(java.awt.Color.WHITE);

        
        txtGaji.setEditable(false);
        txtUpah.setEditable(false);
        txtUpahJam.setEditable(false);
        txtPokok.setEditable(false);
        txtPajak.setEditable(false);
        txtBersih.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupNama = new javax.swing.ButtonGroup();
        lblNama = new javax.swing.JLabel();
        lblNik = new javax.swing.JLabel();
        lblJam = new javax.swing.JLabel();
        lblKaryawan = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNik = new javax.swing.JTextField();
        txtJam = new javax.swing.JTextField();
        cbGol = new javax.swing.JComboBox<>();
        lblUpah = new javax.swing.JLabel();
        txtUpah = new javax.swing.JTextField();
        lblGaji = new javax.swing.JLabel();
        txtGaji = new javax.swing.JTextField();
        lblBersih = new javax.swing.JLabel();
        txtBersih = new javax.swing.JTextField();
        lblPajak = new javax.swing.JLabel();
        txtPajak = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        lblPokok = new javax.swing.JLabel();
        txtPokok = new javax.swing.JTextField();
        lblUpahJam = new javax.swing.JLabel();
        txtUpahJam = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNama.setText("Nama");

        lblNik.setText("NIK");

        lblJam.setText("Jam Kerja");

        lblKaryawan.setText("From Penggajian karyawan");

        cbGol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Golongan", "Golongan 1", "Golongan 2", "Golongan 3", "Golongan 4", " " }));
        cbGol.addActionListener(this::cbGolActionPerformed);

        lblUpah.setText("Total Upah");

        txtUpah.addActionListener(this::txtUpahActionPerformed);

        lblGaji.setText("Total Gaji");

        lblBersih.setText("Gaji Bersih");

        lblPajak.setText("Pajak");

        txtPajak.addActionListener(this::txtPajakActionPerformed);

        btnHitung.setText("Hitung Gaji");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        lblPokok.setText("Gaji Pokok");

        lblUpahJam.setText("Upah Jam");

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPajak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblGaji)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblUpah, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUpah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblJam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUpahJam)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPokok)
                                .addComponent(lblBersih))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKaryawan)
                            .addComponent(txtPokok, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpahJam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(btnReset)
                        .addGap(67, 67, 67)
                        .addComponent(btnKeluar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHitung)
                        .addGap(326, 326, 326)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblKaryawan)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNik)
                            .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJam)
                            .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpah)
                    .addComponent(txtUpah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBersih)
                    .addComponent(txtBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGaji)
                    .addComponent(lblPokok)
                    .addComponent(txtPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPajak)
                    .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpahJam)
                    .addComponent(txtUpahJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUpahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpahActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed


    try{

        if(txtNama.getText().isEmpty() || txtNik.getText().isEmpty() || txtJam.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Data belum lengkap");
            return;
        }

        int jam = Integer.parseInt(txtJam.getText());

        if(jam < 0){
            JOptionPane.showMessageDialog(this,"Jam kerja tidak boleh negatif");
            return;
        }

        if(cbGol.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Pilih golongan terlebih dahulu");
            return;
        }

        double gajiPokok = 0;
        double upahJam = 0;

        switch(cbGol.getSelectedIndex()){

            case 1:
                gajiPokok = 2000000;
                upahJam = 20000;
                break;

            case 2:
                gajiPokok = 3000000;
                upahJam = 30000;
                break;

            case 3:
                gajiPokok = 2750000;
                upahJam = 40000;
                break;

            case 4:
                gajiPokok = 4500000;
                upahJam = 50000;
                break;
        }

        double totalUpah = jam * upahJam;
        double totalGaji = gajiPokok + totalUpah;
        double pajak = totalGaji * 0.025;
        double gajiBersih = totalGaji - pajak;

        txtPokok.setText(Double.toString(gajiPokok));
        txtUpahJam.setText(Double.toString(upahJam));
        txtUpah.setText(Double.toString(totalUpah));
        txtGaji.setText(Double.toString(totalGaji));
        txtPajak.setText(Double.toString(pajak));
        txtBersih.setText(Double.toString(gajiBersih));

    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this,"Jam kerja harus berupa angka");
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage());
    }


     
    }//GEN-LAST:event_btnHitungActionPerformed

    private void txtPajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPajakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPajakActionPerformed

    private void cbGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGolActionPerformed
        
    }//GEN-LAST:event_cbGolActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNama.setText("");
        txtNik.setText("");
        txtJam.setText("");
        cbGol.setSelectedIndex(0);
        txtGaji.setText("");
        txtUpah.setText("");
        txtUpahJam.setText("");
        txtPokok.setText("");
        txtPajak.setText("");
        txtBersih.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
         int pil = JOptionPane.showConfirmDialog(this, "Apakah ingin keluar?","Konfirmasi Keluar",JOptionPane.YES_NO_CANCEL_OPTION);
        
        if(pil==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FromKaryawan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupNama;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbGol;
    private javax.swing.JLabel lblBersih;
    private javax.swing.JLabel lblGaji;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblKaryawan;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNik;
    private javax.swing.JLabel lblPajak;
    private javax.swing.JLabel lblPokok;
    private javax.swing.JLabel lblUpah;
    private javax.swing.JLabel lblUpahJam;
    private javax.swing.JTextField txtBersih;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtPajak;
    private javax.swing.JTextField txtPokok;
    private javax.swing.JTextField txtUpah;
    private javax.swing.JTextField txtUpahJam;
    // End of variables declaration//GEN-END:variables
}